Install docs dependencies
================

<!-- WARNING: THIS FILE WAS AUTOGENERATED! DO NOT EDIT! -->

``` python
from contextlib import contextmanager

import pytest
```

``` python
@contextmanager
def _clean_path():
    path = os.environ["PATH"]
    try:
        os.environ["PATH"] = ""
        yield
    finally:
        os.environ["PATH"] = path
```

``` python
_check_npm()
```

``` python
with _clean_path():
    with pytest.raises(RuntimeError) as e:
        await _check_npm()

assert (
    e.value.args[0]
    == "npm not found, to use documentation generation features of FastKafka, you must have npm >= 9 installed"
)
```

``` python
with pytest.raises(RuntimeError) as e:
    await _check_npm(required_major_version=999)

assert (
    e.value.args[0]
    == "Found installed npm major version: 9, required npx major version: 999. To use documentation features of FastKafka, please update npm"
), e.value.args[0]
```

``` python
_check_npm_with_local()
```

``` python
# Not reentrant because when local is installed, it will break

with _clean_path():
    with pytest.raises(RuntimeError) as e:
        _check_npm_with_local()

assert (
    e.value.args[0]
    == "npm not found, to use documentation generation features of FastKafka, you must have npm >= 9 installed"
)
```

``` python
# Breaks because other tests running in parallel are using already installed node

_install_node()
```

    [INFO] __main__: Installing NodeJS...

      0%|          | 0/184668 [00:00<?, ?it/s]

    [INFO] __main__: Node installed in /home/davor/.local/node-v18.15.0-linux-x64.

``` python
with _clean_path():
    _check_npm_with_local()
```

    [INFO] __main__: Found local installation of NodeJS.

``` python
# Breaks because other tests running in parallel are using already installed node

await _install_docs_npm_deps()
```

    [INFO] __main__: AsyncAPI generator installed
